package com.conduent.nationalhighways.utils.common

import com.conduent.nationalhighways.BuildConfig

object Constants {
    const val landingPageName: String = "Android Dart Charge: Landing Page"
    const val contactPageName: String = "Android Dart Charge: Contact Dart Charge"
    const val chargesAndFinesPageName: String = "Android Dart Charge: Charges and fines"
    const val aboutServicePageName: String = "Android Dart Charge: About this service"
    const val generalTermsAndConditionsPageName: String = "Android Dart Charge: Terms and Conditions"
    const val termsAndConditionsPageName: String = "Android Dart Charge: Terms and Conditions - General"
    const val paygTermsAndConditionsPageName: String = "Android Dart Charge: Terms and Conditions - PAYG"
    const val TWOFA_ENABLED: String = "TWOFA_ENABLED"
    const val HAS_ASKED_FOR_BIOMETRIC: String = "HAS_ASKED_FOR_BIOMETRIC"
    const val privacyPolicyPageName: String = "Android Dart Charge: Privacy Policy"
    const val BIOMETRIC_CHANGE: String = "BIOMETRIC_CHANGE"
    const val otherWaysToPayPageName: String = "Android Dart Charge: Other ways to pay your charge"
    const val doYouHaveDartAccountPageName: String = "Android Dart Charge Non-Account Holder: Have a Dart Charge account?"
//    const val termsAndConditionsPageName: String = "Android Dart Charge: Terms and Conditions"
//    const val termsAndConditionsPageName: String = "Android Dart Charge: Terms and Conditions"

    //About us
//    case otherWaysToPay = "iOS Dart Charge: Other ways to pay your charge"
//    case thirdPartySoftware = "iOS Dart Charge: Third party software"
//
//    //Raise a new enquiry
//    case doYouHaveDartAccount = "iOS Dart Charge Non-Account Holder: Have a Dart Charge account?"
//    case categoryAndSubCategoryNonAccount = "iOS Dart Charge Non-Account Holder: Category and Sub-category type"
//    case moreDetailsNonAccount = "iOS Dart Charge Non-Account Holder: More detail"
//    case enquiryContactDetailsNonAccount = "iOS Dart Charge Non-Account Holder: Enquiry contact details"
//    case summeryPageNonAccount = "iOS Dart Charge Non-Account Holder: Summary page"
//    case enquiryStatusNonAccount = "iOS Dart Charge Non-Account Holder: Enquiry status"
//    case enquirySuccessNonAccount = "iOS Dart Charge Non-Account Holder: Enquiry success"
//    case enquiryHistory = "iOS Dart Charge Account Holder: Enquiry History"
//    case categoryAndSubCategoryAccount = "iOS Dart Charge Account Holder: Category and Sub-category type"
//    case moreDetailsAccount = "iOS Dart Charge Account Holder: More detail"
//    case enquiryContactDetailsAccount = "iOS Dart Charge Account Holder: Enquiry contact details"
//    case summeryPageAccount = "iOS Dart Charge Account Holder: Summary page"
//    case enquirySuccessAccount = "iOS Dart Charge Account Holder: Enquiry success"
//
//    //Acccount creation
//    case beforeYouStart = "iOS Dart Charge: Account Creation: Before you start"
//    case typeOfAccount = "iOS Dart Charge: Account Creation: Type of account"
//    case creationName = "iOS Dart Charge: Account Creation: Name"
//    case addressPostCode = "iOS Dart Charge: Account Creation: Address postcode"
//    case selectAddress = "iOS Dart Charge: Account Creation: Select address"
//    case selectOfficeAddress = "iOS Dart Charge: Account Creation: Select office address"
//    case manualAddress = "iOS Dart Charge: Account Creation: Manual address"
//    case officeManualAddress = "iOS Dart Charge: Account Creation: Office manual address"
//    case ldrsEligible = "iOS Dart Charge: Account Creation: LRDS eligible"
//    case prePayOrPayG = "iOS Dart Charge: Account Creation: Prepay or PAYG"
//    case crossigCharges = "iOS Dart Charge: Account Creation: Crossing charges"
//    case createEmail = "iOS Dart Charge: Account Creation: Email"
//    case verifyEmail = "iOS Dart Charge: Account Creation: Verify email"
//    case requestEmailCode = "iOS Dart Charge: Account Creation: Request email code"
//    case createPassword = "iOS Dart Charge: Account Creation: Create password"
//    case optInTp2FA = "iOS Dart Charge: Account Creation: Opt in to 2FA"
//    case captureWhetherOnOrOff = "iOS Dart Charge: Account Creation: Text message communications - Capture whether on/ off"
//    case captureWhetherOn = "iOS Dart Charge: Account Creation: Text message communications - Capture whether on"
//    case captureWhetherOff = "iOS Dart Charge: Account Creation: Text message communications - Capture whether off"
//    case mobileNumber = "iOS Dart Charge: Account Creation: Mobile number"
//    case verifyMobile = "iOS Dart Charge: Account Creation: Verify mobile"
//    case requestPhoneCode = "iOS Dart Charge: Account Creation: Request phone code"
//    case landLineNumber = "iOS Dart Charge: Account Creation: Landline number"
//    case numberPlate = "iOS Dart Charge: Account Creation: Number plate"
//    case vehicleExempt = "iOS Dart Charge: Account Creation: Vehicle exempt"
//    case vehicleZeroRate = "iOS Dart Charge: Account Creation: Vehicle zero rate"
//    case vehicleAlredyToAnotherAccoount = "iOS Dart Charge: Account Creation: Vehicle already on another account"
//    case vehicleAlreadyAdded = "iOS Dart Charge: Account Creation: Vehicle already added"
//    case maximumVehicleAdded = "iOS Dart Charge: Account Creation: Maximum vehicles added"
//    case vehicleLookingFor = "iOS Dart Charge: Account Creation: Vehicle looking for?"
//    case vehicleAddedSummery = "iOS Dart Charge: Account Creation: Vehicle added/ summary"
//    case removeVehicleQuestion = "iOS Dart Charge: Account Creation: Remove vehicle?"
//    case vehicleMoreInformationNotFount = "iOS Dart Charge: Account Creation: Vehicle more information - not found"
//    case vehicleMoreInformationUK = "iOS Dart Charge: Account Creation: Vehicle more information - UK"
//    case vehicleMoreInformationNonUK = "iOS Dart Charge: Account Creation: Vehicle more information - non-UK"
//    case vehicleUkNon_UK = "iOS Dart Charge: Account Creation: Vehicle UK/ Non-UK"
//    case mustRegisterAtLeast1Vehicle = "iOS Dart Charge: Account Creation: Must register at least 1 vehicle"
//    case payment = "iOS Dart Charge: Account Creation: Payment"
//    case paymentPayG = "iOS Dart Charge: Account Creation: Payment PAYG"
//    case checkYourAnswer = "iOS Dart Charge: Account Creation: Check your answers"
//    case topUpAmount = "iOS Dart Charge: Account Creation: Top up amount"
//    case accountConfirmationPAYG = "iOS Dart Charge: Account Creation: Account confirmation PAYG"
//    case accountConfirmationPrePay = "iOS Dart Charge: Account Creation: Account confirmation Pre-Pay"
//    case paymentError = "iOS Dart Charge: Account Creation: Payment error"
//
//    //dashboard
//    case dashbooardSuspendAccoout = "iOS Dart Charge: Dashboard: Suspended account"
//    case dashbooardActiveAccoout = "iOS Dart Charge: Dashboard: Active account"
//    case accountManagement = "iOS Dart Charge: Account Management"

    const val DIRECT_DEBIT: String = "directdebit"
    const val IS_DIRECT_DEBIT: String = "IS_DIRECT_DEBIT"
    const val FIND_VEHICLE = "FIND_VEHICLE"
    const val DIRECT_DEBIT_DELETE = "direct_debit_delete"
    const val DIRECT_DEBIT_NOT_SET_UP = "direct_debit_not_set_up"
    const val CREDIT_NOT_SET_UP = "credit_not_set_up"
    const val ACCOUNT_CLOSURE = "ACCOUNT CLOSURE"
    const val ACCOUNT_HOLDER_REQUEST = "ACCOUNT HOLDER REQUEST"
    const val Mobile_App = "Mobile App"
    const val NEW_CARD = "newcard"
    const val IS_EDIT_EMAIL = "isEditEmail"
    const val MONTHLY = "MONTHLY"
    const val ACTIVE = "ACTIVE"
    const val MAKE_DEFAULT = "make_default"
    const val FROM_ALL_TRANSACTIONS_TO_DETAILS = "FROM_ALL_TRANSACTIONS_TO_DETAILS"
    const val PERSONALDATA = "personaldata"
    const val ACCOUNTINFORMATION = "accountinformation"
    const val REPLENISHMENTINFORMATION = "ReplenishmentInformation"
    const val EXISTING_CARD = "existing_card"
    const val EXPIRED = "EXPIRED"
    const val CURRENT = "CURRENT"
    const val SAVINGS = "SAVINGS"
    const val MASTERCARD = "MASTERCARD"
    const val MAESTRO = "MAESTRO"
    const val CASH = "CASH"
    const val VISA = "VISA"
    const val RETRY_COUNT = 3
    const val ITEM_COUNT: Long = 20
    const val LOCAL_APP_SESSION_TIMEOUT = 1000 * 60 * 15L

    const val SPLASH_TIME_OUT = 500L
    const val COUNTRY_TYPE = "country_type"
    const val CHECK_PAID_CROSSING_VRM_ENTERED = "CHECK_PAID_CROSSING_VRM_ENTERED"
    const val CHECK_PAID_CROSSING_VRM_EXISTS = "CHECK_PAID_CROSSING_VRM_EXISTS"
    const val CHECK_PAID_CROSSINGS_VRM_DETAILS = "CHECK_PAID_CROSSINGS_VRM_DETAILS"
    const val CHECK_PAID_CHARGE_DATA_KEY = "from_check_paid_ref_data_to_check_list"
    const val CHECK_PAID_REF_VRM_DATA_KEY = "from_check_paid_ref_data_to_ref_vrm"
    const val FROM_CREATE_ACCOUNT_SUMMARY_TO_EDIT_PAYMENT =
        "FROM_CREATE_ACCOUNT_SUMMARY_TO_EDIT_PAYMENT"
    const val FROM_CREATE_ACCOUNT_SUMMARY_TO_EDIT_EMAIL =
        "FROM_CREATE_ACCOUNT_SUMMARY_TO_EDIT_EMAIL"
    const val FROM_CREATE_ACCOUNT_SUMMARY_TO_EDIT_ACCOUNT_TYPE =
        "FROM_CREATE_ACCOUNT_SUMMARY_TO_EDIT_ACCOUNT_TYPE"
    const val FROM_DASHBOARD_TO_CROSSING_HISTORY = 1001
    const val FROM = "from"
    const val UK_VEHICLE_DATA_NOT_FOUND_KEY = "uk_vehicle_data_not_found_key"
    const val ONE_OF_PAYMENTS_PAY_RESP = "one_of_payments_model_res"
    const val OPTIONS_TYPE = "Options_type"
    const val NOMINATED_ACCOUNT_DATA = "nominee_data"
    const val NOMINATED_ACCOUNT = "NOMINATED"
    const val PENDING_STATUS = "PENDING"
    const val CATEGORY_RECEIPTS = "Standard Notification"
    const val LRDS_ELIGIBILITY_CHECK = "lrdsEligibilityCheck"

    const val COUNTRY_TYPE_UK = "UK"
    const val COUNTRY_TYPE_NON_UK = "NON UK"
    const val CASE_COMMENTS_KEY = "case_comments_key"
    const val CASES_CATEGORY = "cases_category"
    const val CASES_SUB_CATEGORY = "cases_sub_category"
    const val PAYG = "PAYG"
    const val EXEMPT_PARTNER = "EXEMPT PARTNER"
    const val PAYMENT_HISTORY = "payment_history"
    const val PAYMENT_METHOD = "payment_method"
    const val ADD_PAYMENT_METHOD = "add_payment_method"
    const val PAYMENT_TOP_UP = "payment_top_up"
    const val DASHBOARD = "dashboard"
    const val TOP_UP_AMOUNT = "top_up_amount"
    const val PERSONAL_TYPE = "personal_type_pre_pay_or_pay_as_go"
    const val FROM_DART_CHARGE_FLOW = "from_dart_charge_flow"
    const val NORMAL_LOGIN_FLOW_CODE = 1001
    const val DART_CHARGE_FLOW_CODE: Int = 1002
    const val FROM_LOGIN_TO_CASES_VALUE = 1003
    const val FROM_CASES_TO_CASES_VALUE = 1004
    const val FROM_ANSWER_TO_CASE_VALUE = 1012

    const val PERSONAL_TYPE_PREPAY = 1005
    const val PERSONAL_TYPE_PAY_AS_U_GO = 1006
    const val UK_VEHICLE_DATA_NOT_FOUND = 1007
    const val FROM_CREATE_ACCOUNT_SUMMARY_TO_EDIT_PAYMENT_KEY = 1008
    const val FROM_CREATE_ACCOUNT_SUMMARY_TO_EDIT_EMAIL_KEY = 1009
    const val FROM_CREATE_ACCOUNT_SUMMARY_TO_EDIT_ACCOUNT_TYPE_KEY = 1010
    const val FROM_CREATE_ACCOUNT_DETAILS_FRAG_TO_CREATE_ACCOUNT_FIND_VEHICLE = 1011


    const val FILE_NAMES_KEY = " file_names_key"

    const val CASES_PROVIDE_DETAILS_KEY = "provide_case_details"

    const val FROM_LOGIN_TO_CASES = "FROM_LOGIN_TO_CASES"
    const val PERSONAL_DETAILS = "personal_details"
    const val POST_CODE_ADDRESS = "post_code_address"
    const val PASSWORD = "password"
    const val PIN = "pin"
    const val LRDS_SCREEN = "lrds_screen"
    const val STATUS_TERMINATED = "TERMINATED"

    const val TRANSACTION_DATE = "Transaction Date"
    const val MAIN_ACCOUNT = "main_account"
    const val SUB_ACCOUNT = "sub_account"
    const val VPN_ERROR = "Check your network connection."
    const val API_TIME_OUT = "Api timeout"
    const val REFRESH_TOKEN = "refresh_token_to_start"
    const val TYPE = "type"
    const val LOGIN = "login"
    const val START_NOW = "start_now"
    const val SESSION_TIME_OUT = "session_time_out"
    const val START_NOW_SCREEN = "start_now"
    const val LOGOUT_SCREEN = "log_out"
    const val FAILED_RETRY_SCREEN = "failed_retry"
    const val SERVICE_UNAVAILABLE = "service_unavailable"
    const val LANDING_SCREEN = "landing"
    const val TOLL_TRANSACTION = "Toll_Transaction"
    const val ALL_TRANSACTION = "ALL"
    const val SPREAD_SHEET = "spreadsheet"
    const val PDF = "pdf"
    const val VIEW_ALL = "view_all"
    const val ALL = "ALL"
    const val DATE_FILTER = "date_filter"
    const val TERMSCONDITIONURL = "termsConditionUrl"
    const val NO = "no"
    const val YES = "yes"
    const val Y = "Y"
    const val N = "N"
    const val APPLE_PAY = "apple_pay"
    const val GOOGLE_PAY = "google_pay"
    const val PAY_PAL = "pay_pal"
    const val QUICK_PAYMENT = "quick_payment"
    const val BANK_TRANSFER = "bank_transfer"
    const val CARD_PAYMENT = "card_payment"
    const val OPTIONS = "options"
    const val EMAIL_MODE = 1
    const val MESSAGE_MODE = 2
    const val POST_MAIL_MODE = 3
    const val POST_CODE = "post_code"
    const val EDIT_POST_CODE = "edit_post_code"
    const val DATA = "data"
    const val ALLOWED_CHARACTERS_IN_PASSWORD = "~!@#\$%^&*_-+=`|\\(){}[]:;\"'<>,.?/"
    const val LOWER_CASE_ALPHABETS = "qwertyuiopasdfghjklzxcvbnm"
    const val UPPER_CASE_ALPHABETS = "QWERTYUIOPASDFGHJKLZXCVBNM"
    const val ALLOWED_CHARACTERS_IN_EMAIL = "-._+"
    const val ALLOWED_CHARACTERS_IN_ADDRESS = "',.-"
    const val ALLOWED_CHARACTERS_IN_POSTCODE = "',.-"

    const val CURRENTBALANCE = "currentBalance"
    const val SUSPENDED = "suspended"
    const val PAYG_SUSPENDED = "payg_suspended"
    const val NOTSUSPENDED = "notsuspended"
    const val THRESHOLD_AMOUNT = "threshold_amount"
    const val THRESHOLD = "threshold_amount"
    const val CREATE_ACCOUNT_DATA = "create_account_data"
    const val PLATE_NUMBER = "plateNumber"
    const val OLD_PLATE_NUMBER = "oldPlateNumber"
    const val VEHICLE_INDEX = "vehicle_position"
    const val IS_DBLA_AVAILABLE = "isDblaAvailable"
    const val DATA2 = "list2"
    const val POST_MAIL = "MAIL"
    const val SMS = "SMS"
    const val EMAIL = "EMAIL"
    const val MOBILE_NUMBER = "MOBILE_NUMBER"
    const val ACCOUNT_SUBTYPE = "ACCOUNT_SUBTYPE"
    const val Email = "Email"
    const val MODE = "mode"
    const val CREATE_ACCOUNT = "CREATE ACCOUNT"
    const val VIEW_CHARGES = "VIEW CHARGES"
    const val CHECK_FOR_PAID = "CHECK FOR PAID CROSSINGS"
    const val RESOLVE_PENALTY = "RESOLVE PENALTY"
    const val ONE_OFF_PAYMENT = "ONE OFF PAYMENT"
    const val ONE_OFF_PAYMENT_SUCCESS = "ONE OFF PAYMENT SUCCESS"
    const val CHECK_FOR_PAID_CROSSINGS = "CHECK_FOR_PAID_CROSSINGS"
    const val CHECK_FOR_PAID_CROSSINGS_ONEOFF = "CHECK_FOR_PAID_CROSSINGS_ONEOFF"
    const val PAYMENT_RESPONSE = "payment_resp"
    const val PAYMENT_DATA = "payment_data"
    const val PAYMENT_METHOD_SIZE = "payment_method_size"
    const val VEHICLE_DATA = "vehicle_data"
    const val VEHICLE_SCREEN_TYPE_LIST = 1
    const val VEHICLE_SCREEN_TYPE_ADD = 2
    const val VEHICLE_SCREEN_TYPE_ADD_ONE_OF_PAYMENT = 3
    const val VEHICLE_SCREEN_TYPE_HISTORY = 4
    const val VEHICLE_SCREEN_TYPE_CROSSING_HISTORY = 5
    const val VEHICLE_SCREEN_KEY = "com.heandroid.VehicleMgmtActivity.SCREEN"
    const val FROM_DASHBOARD_TO_VEHICLE_LIST = "com_heandroid_dashboard_to_vehiclelist"
    const val VEHICLE_RESPONSE = "vehicle_api_resp"
    const val SHOW_SCREEN = "show_screen"
    const val ABOUT_SERVICE = "about_service"
    const val CONTACT_DART_CHARGES = "contact_dart_charges"
    const val CROSSING_SERVICE_UPDATE = "crossing_service_update"
    const val DART_CHARGE_GUIDANCE_AND_DOCUMENTS = "dart_charge_guidance_documents"

    const val LANGUAGE = "ENU"
    const val ALERT_ITEM_KEY = "cscLookupKey"
    const val PERSONAL_ACCOUNT = "PRIVATE"
    const val PREPAY_ACCOUNT = "STANDARD"
    const val BUSINESS_ACCOUNT = "BUSINESS"
    const val EXEMPT_ACCOUNT = "NONREVENUE"
    const val PRE_PAY_ACCOUNT = "pre_pay_account"
    const val STANDARD = "STANDARD"
    const val PRIORITY = "PRIORITY"
    const val PAYG_ACCOUNT = "pay_as_you_go_account"
    const val UK = "UK"
    const val NON_UK = "Non UK"
    const val PAYMENT_PAGE = "payment page"
    const val NMI = "nmi"
    const val MAX_VEHICLE_SIZE = 5
    const val MAX_VEHICLE_SIZE_ONE_OFF_PAY = 1

    const val EMAIL_SELECTION_TYPE = "Email"
    const val REFERENCE_ID = "Reference Id"
    const val AGENCY_ID = BuildConfig.AGENCY_ID
    const val NOT_IN_THE_LIST = "Not in the list"
    const val PHONE_COUNTRY_CODE = "PHONE_COUNTRY_CODE"
    const val FIND_VEHICLE_DATA = "FIND_VEHICLE_DATA"
    const val CASE_NUMBER = "case number"
    const val LAST_NAME = "last name"
    const val CLOSED = "Closed"
    const val PDF_EXTENSION = ".pdf"
    const val CSV_EXTENSION = ".csv"
    const val PCN_RESOLVE_URL =
        "https://www.dartford-crossing-charge.service.gov.uk/PcnPayment/SearchMultiplePCN"
    const val CREATE_ACCOUNT_NON_UK = "CreateAccountNonUKModel"

    const val CHOOSE_FILE_1 = "Choose_first_file"
    const val CHOOSE_FILE_2 = "Choose_second_file"
    const val CHOOSE_FILE_3 = "Choose_third_file"
    const val CHOOSE_FILE_4 = "Choose_fourth_file"
    const val PAYMENT = "Payment"
    const val PAYMENT_FILTER_VEHICLE = "Payment_filter_with_vehicle_number"
    const val PAYMENT_FILTER_SPECIFIC = "Payment_filter_with_specified_date"
    const val PAYMENT_DATE_RANGE = "Payment_filter_with_date_range"
    const val UPDATE_PIN_FLOW = "update pin flow"
    const val VEHICLE_NO = "VehicleNo"
    const val COUNTRY_BUSINESS = "country"
    const val NON_UK_VEHICLE_DATA = "Non_UK_Model"
    const val NO_OF_CROSSING_BUSINESS = "Number_of_crossing"
    const val NO_OF_VEHICLE_BUSINESS = "Number_of_vehicle"
    const val IS_CREATE_VEHICLE_GROUP = "is this flow for delete"
    const val VEHICLE_GROUP = "vehicle_group"
    const val VEHICLE_ROW_ITEM = "Vehicle_Row_Item"
    const val ERROR_DIALOG = "error_dialog"
    const val LOADER_DIALOG = "loader_dialog"
    const val RETRY_DIALOG = "retry_dialog"
    const val SESSION_DIALOG = "session_dialog"
    const val LOGOUT_DIALOG = "logout_dialog"
    const val SEARCH_VEHICLE_DIALOG = "search_vehicle_dialog"
    const val DELETE_VEHICLE_GROUP_DIALOG = "delete_vehicle_group_dialog"
    const val DATE_PICKER_DIALOG = "date_picker_dialog"
    const val CROSSING_HISTORY_FILTER_DIALOG = "crossing_history_filter_dialog"
    const val DOWNLOAD_FORMAT_SELECTION_DIALOG = "download_format_selection_dialog"
    const val LIVE = "LIVE"
    const val MAINTENANCE = "MAINTENANCE"
    const val UNAVAILABLE = "UNAVAILABLE"
    const val SERVICE_TYPE = "SERVICE_TYPE"
    const val END_TIME = "END_TIME"
    const val FROM_DETAILS_FRAG_TO_CREATE_ACCOUNT_FIND_VEHICLE =
        "FROM_DETAILS_FRAG_TO_CREATE_ACCOUNT_FIND_VEHICLE"
    const val VEHICLE_DETAIL = "vehicle detail"
    const val DELETE_CARD = "delete_card"


    const val EMAIL_ADDRESS = "Email address"
    const val PHONE_NUMBER = "Phone number"

    //Biometric
    const val FROM_LOGIN_TO_BIOMETRIC = "FROM_LOGIN_TO_BIOMETRIC"
    const val FROM_LOGIN_TO_BIOMETRIC_VALUE = 1003
    const val FROM_ACCOUNT_TO_BIOMETRIC_VALUE = 1004


    //Error code for api response
    const val NO_DATA_FOR_GIVEN_INDEX = 1020
    const val NO_DATA_FOR_NOTIFICATIONS = 1220
    const val CASES_GIVEN_DATE_WRONG = 1042


    const val data_type = "data_type"
    const val NAV_FLOW_KEY = "navFlowKey"
    const val LRDS_ACCOUNT = "lrds_account"
    const val ADDRESS_LIST = "ADDRESS_LIST"
    const val SAVED_CARDS = "SAVED_CARDS"
    const val NAV_FLOW_FROM = "navFlowFrom"
    const val GO_TO_SUCCESS_PAGE = "GO_TO_SUCCESS_PAGE"
    const val IS_BIOMETRIC_CHANGED = "IS_BIOMETRIC_CHANGED"
    const val FIRST_TYM_REDIRECTS = "FIRST_TYM_REDIRECTS"
    const val NAV_DATA_KEY = "navDataKey"
    const val FROM_SUMMARY_PAGE = "fromSummaryPage"
    const val Edit_REQUEST_KEY = "editRequestKey"
    const val SHOW_BACK_BUTTON = "showBackButton"
    const val IS_MOBILE_NUMBER = "isMobileNumber"
    const val EDIT_FROM_POST_CODE = "editFromPostCode"
    const val AccountType_EMAIL = "AccountType_EMAIL"
    const val AccountType_MobileNumber = "AccountType_MobileNumber"
    const val OPTSMS = "optSms"
    const val TwoStepVerification = "twoStepVerification"
    const val EDIT_SUMMARY = "editSummary"
    const val HAVE_RECENT_CROSSINGS = "haveRecentCrossings"
    const val EDIT_MOBILE = "editmobile"
    const val EDIT_EMAIL = "editEmail"
    const val EDIT_CATEGORY_DATA = "editCategoryData"
    const val EDIT_CATEGORY_DATA_NOCHANGES = "editCategoryDataNoChanges"
    const val EDIT_COMMENTS_DATA = "editCommentsData"
    const val EDIT_CONTACT_DETAILS_DATA = "editContactDetailsData"
    const val PAY_FOR_CROSSINGS = "payForCrossings"
    const val PAID_CROSSINGS = "paidCrossings"
    const val TRANSFER_CROSSINGS = "transferCrossings"
    const val EDIT_ACCOUNT_TYPE = "editAccountType"
    const val EDIT_PROFILE = "editProfile"
    const val VEHICLE_MANAGEMENT = "vehicleManagement"
    const val PROFILE_MANAGEMENT = "profileManagement"
    const val PROFILE_MANAGEMENT_ADDRESS_CHANGED = "profileManagementAddressChanged"
    const val PROFILE_MANAGEMENT_COMMUNICATION_CHANGED = "profileManagementCommunicationChanged"
    const val PROFILE_MANAGEMENT_MOBILE_CHANGE = "profileManagementMobileChange"
    const val PROFILE_MANAGEMENT_2FA_CHANGE = "profileManagement2faChange"
    const val PROFILE_MANAGEMENT_EMAIL_CHANGE = "PROFILE_MANAGEMENT_EMAIL_CHANGE"
    const val PROFILE_TWO_FACTOR_VERIFICATION = "Profile Two Factor Verification"
    const val TWOFA = "twofa"
    const val ACCOUNT_CREATION_EMAIL_FLOW = "accountCreationEmailFlow"
    const val FORGOT_PASSWORD_FLOW = "forgotPasswordFlow"
    const val ACCOUNT_CREATION_MOBILE_FLOW = "accountCreationMobileFlow"
    const val IS_PERSONAL_ACCOUNT = "isPersonalAccount"
    const val POSTCODE = "postcode"
    const val POSITION = "position"
    const val UK_COUNTRY = "United Kingdom"
    const val USA = "USA"
    const val USA_CODE = "USA +1"
    const val UNITED_KINGDOM = "United Kingdom (+44)"
    const val LIST = "list"
    const val REMOVE_VEHICLE = "remove_vehicle"
    const val EDIT_VEHICLE = "edit_vehicle"
    const val CROSSINGCOUNT = "crossingCount"
    const val TRANSACTIONID = "tranasactionId"
    const val LOW_BALANCE = "lowbalance"
    const val LOW_BALANCE_AMOUNT = "lowbalanceamount"
    const val CARD_IS_ALREADY_REGISTERED = "card_is_already_registered"
    const val SECONDARY_CARD_DELETE = "secondary_card_delete"
    const val NOT_SECONDARY_CARD_DELETE = "not_secondary_card_delete"
    const val ACCOUNT_NUMBER = "account_number"

    const val TOP_UP_BALANCE = "top_up_balance"
    const val EnquiryResponseModel = "EnquiryResponseModel"
    const val HISTORY_LIST = "history_list"
    const val ENQUIRY_STATUS = "enquiry_status"
    const val ACCOUNT_CONTACT_US = "account_contact_us"
    const val IS_IT_MOBILE_NUMBER = "is_it_mobile_number"
    const val COUNT = "COUNT"

    const val API_TIMEOUT_ERROR = 100100
    const val TOKEN_FAIL = 401
    const val INTERNAL_SERVER_ERROR = 500
    const val INVALID_TOKEN = "invalid_token"
    const val SERVER_ERROR = "server_error"
    const val API_STATE = "API_STATE"
    const val API_END_TIME = "API_END_TIME"
    const val CARD_VALIDATION_REQUIRED = "cardValidationRequired"
    const val READ_STORAGE_REQUEST_CODE: Int = 1001
    const val TIME_OUT_SEC = 80L


    //Notification Types
    const val GEO_FENCE_NOTIFICATION = "geofenceNotification"


    //DateFormats
    const val dd_mm_yyyy_hh_mm_ss = "dd/MM/yyyy HH:mm:ss"

    const val GpsSettings = "GpsSettings"
    const val geofenceNorthBoundDartCharge = "geofenceNorthBoundDartCharge"
    const val geofenceSouthBoundDartCharge = "geofenceSouthBoundDartCharge"

    const val FOREGROUND_SERVICE_NOTIFICATIONID=12334

}
